name: Android APK (gera .apk direto)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Provisiona o Gradle 8.2 e habilita cache
      - name: Setup Gradle 8.2
        uses: gradle/actions/setup-gradle@v3.5.0
        with:
          gradle-version: 8.2

      # Mostrar módulos e tasks disponíveis (ajuda a depurar)
      - name: Show Gradle projects & tasks
        shell: bash
        run: |
          if [ -x ./gradlew ]; then
            ./gradlew projects
            ./gradlew tasks --all
          else
            gradle projects
            gradle tasks --all
          fi

      # --- APK DEBUG ---
      - name: Build DEBUG APK
        shell: bash
        run: |
          if [ -x ./gradlew ]; then
            ./gradlew clean assembleDebug
          else
            gradle clean assembleDebug
          fi

      - name: Upload DEBUG APK
        uses: actions/upload-artifact@v4
        with:
          name: IboPlus-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      # --- APK RELEASE ---
      - name: Build RELEASE APK
        shell: bash
        run: |
          if [ -x ./gradlew ]; then
            ./gradlew clean assembleRelease
          else
            gradle clean assembleRelease
          fi

      - name: Upload RELEASE APK
        uses: actions/upload-artifact@v4
        with:
          name: IboPlus-release-apk
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: warn
