name: Android APK (gera .apk direto)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Força Gradle 8.2 (evita usar Gradle 9.x que quebrou seu build)
      - name: Setup Gradle 8.2
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.2

      # --- Build APK DEBUG (instalável sem assinatura release) ---
      - name: Build DEBUG APK
        run: |
          ./gradlew clean :app:assembleDebug

      - name: Upload DEBUG APK
        uses: actions/upload-artifact@v4
        with:
          name: IboPlus-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      # --- Opcional: Build Release APK ---
      - name: Build RELEASE APK
        run: |
          ./gradlew clean :app:assembleRelease

      - name: Upload RELEASE APK
        uses: actions/upload-artifact@v4
        with:
          name: IboPlus-release-apk
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: warn
